<Home>:
	orientation: 'vertical'
	
	ScreenManager:
		id: sm
		Screen:
			name: 'home'
			Status_bar:
				id: statusbar
				size_hint: 1,.1
			Home_Page:
			Status_bar:
				id: statusbar
				size_hint: 1,.1
				background_color: 1,1,1,1
		Screen:
			name: 'guest_and_author'
			Guest_and_Author:
		Screen:
			name: 'create_account'
			Label:

		Screen:
			name: 'download_pdf'
			Download_Pdf:
				id: download_pdf
		Screen:
			name: 'author_signup'
			Author_Signup: